package main

import (
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestUpperCaseHandler(t *testing.T) {
	// NewRequest returns a new incoming server Request,
	// suitable for passing to an http.Handler for testing.
	req := httptest.NewRequest(http.MethodGet, "/upper?word=abcd", nil)

	// ResponseRecorder is an implementation of http.ResponseWriter
	// that records its mutations for later inspection in tests.
	w := httptest.NewRecorder()
	UpperCaseHandler(w, req)

	// Result returns the response generated by the handler.
	res := w.Result()
	defer res.Body.Close()
	data, err := ioutil.ReadAll(res.Body)

	if err != nil {
		t.Errorf("There is an error: %v", err)
	}
	if string(data) != "ABCD" {
		t.Errorf("Expected ABCD got %v", string(data))
	}
}
